### ISSUE TITLE
Why would I use this over REST if you don't return structs?

### ISSUE THREAD

**Issue by austincollinpena** [serpapi/google-search-results-golang#3]
I don't think it's very useful to me if I have to cast everything into an interface first compared decoding the JSON into a struct.

**Comment by Raallen89** [comment]
> I don't think it's very useful to me if I have to cast everything into an interface first compared decoding the JSON into a struct.

**Comment by austincollinpena** [comment]
This seems like an SEO play that doesn't bring value to users, just exists to be on Github where users can find your service.
